services:
  web:
    image: planning-poker-web:dev
    build:
      target: development
    volumes:
      - ./web:/web
    environment:
      REACT_APP_VERSION: "development"
  api:
    image: planning-poker-api:dev
    build:
      target: development
    volumes:
      - ./api:/api
    environment:
      VERSION: "development"
