services:
  web:
    image: registry.hrgn.dk/planning-poker-web:dev
    build:
      context: web
      target: development
    stop_grace_period: 1s
    ports:
      - "80:80"
    volumes:
      - ./web:/web
  api:
    image: registry.hrgn.dk/planning-poker-api:dev
    build:
      context: api
      target: development
    stop_grace_period: 1s
    ports:
      - "3000:3000"
    volumes:
      - ./api:/api
