services:
  web:
    image: registry.hrgn.dk/planning-poker-web-new:${TAG:-prod}
    build:
      target: production
  api:
    image: registry.hrgn.dk/planning-poker-api-new:${TAG:-prod}
    build:
      target: production
