services:
  web:
    build:
      context: web
      target: development
    stop_grace_period: 1s
    ports:
      - "80:80"
    volumes:
      - ./web:/web
    environment:
      REACT_APP_VERSION: "development"
  api:
    build:
      context: api
      target: development
    stop_grace_period: 1s
    ports:
      - "3000:3000"
    volumes:
      - ./api:/api
    environment:
      VERSION: "development"